### ISSUE TITLE
Update Report flow functionality

### ISSUE THREAD

**Issue by carolineh101** [ashi-agrawal/SafeCity-Android#5]
- [x] Persist data using Report model
- [x] Remove Report button from Step 3 fragment 
- [x] Remove Next button from Step 1 fragment
- [x] Toast user if required fields not filled out when "Confirm" pressed
- [x] Implementations of above using a complete Report model

**Comment by ashi-agrawal** [comment]
Removed Report button from Step 3 fragment and removed Next button from Step 1 fragment with commit 07596f667754fdc8b148c382dd9f54ecf1d4f3b2.

**Comment by ashi-agrawal** [comment]
It seems as though swiping to another Fragment might trigger onPause() not onDestroy(). Make not to include additional overhead by autofilling Fragments if there's no need to do so.
